namespace Task.Migrations
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Globalization;
    using System.Linq;
    using Task.Models;

    internal sealed class Configuration : DbMigrationsConfiguration<Task.Models.Taskcontext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
        }


        protected override void Seed(Task.Models.Taskcontext context)
        {
            var AccountClass = new List<AccountClass>
            {

             new AccountClass {Id=1,AccountClassName="Assets",NormalBalance="Dr"
             },
new AccountClass {Id=2,AccountClassName="Liabilities",NormalBalance="Cr" },
new AccountClass {Id=3,AccountClassName="Equity",NormalBalance="Cr" },
new AccountClass {Id=4,AccountClassName="Revenue",NormalBalance="Cr" },
new AccountClass {Id=5,AccountClassName="Expense",NormalBalance="Dr" }

            };

            AccountClass.ForEach(x => context.AccountClass.Add(x));
            context.SaveChanges();

            var accounttype = new List<AccountType>
            {
 new AccountType {id=1,AccountTypeCode="R",AccountTypeDesc="Root Account",AccountLevel=0},
 new AccountType {id=2,AccountTypeCode="M",AccountTypeDesc="Main Bransh Account",AccountLevel=1},
 new AccountType {id=3,AccountTypeCode="S",AccountTypeDesc="Sub Bransh Account",AccountLevel=2},
 new AccountType {id=4,AccountTypeCode="L",AccountTypeDesc="Local Bransh Account",AccountLevel=3},
 new AccountType {id=5,AccountTypeCode="C",AccountTypeDesc="Child Account",AccountLevel=4},
 new AccountType {id=6,AccountTypeCode="D",AccountTypeDesc="Detail Account",AccountLevel=5}


            };

            accounttype.ForEach(x => context.AccountType.Add(x));
            context.SaveChanges();



            var accounts = new List<Accounts>
            {


 new Accounts {ID=1,CompanyId=1,AccountCode=100000,ParentAccountCode=0,AccountName="Assets",AccountOrder=1,AccountClassID=1,AccountTypeCode=1,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/17/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/17/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=2,CompanyId=1,AccountCode=100001,ParentAccountCode=100000,AccountName="Fixed Assets",AccountOrder=2,AccountClassID=1,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/18/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/18/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=3,CompanyId=1,AccountCode=100002,ParentAccountCode=100001,AccountName="Office Furniture & Fixtures",AccountOrder=3,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/19/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/19/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=4,CompanyId=1,AccountCode=100003,ParentAccountCode=100001,AccountName="Vehicles",AccountOrder=4,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/20/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/20/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=5,CompanyId=1,AccountCode=100004,ParentAccountCode=100001,AccountName="Plants & Equipments",AccountOrder=5,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/21/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/21/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=6,CompanyId=1,AccountCode=100005,ParentAccountCode=100001,AccountName="Buildings",AccountOrder=6,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/22/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/22/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=7,CompanyId=1,AccountCode=100006,ParentAccountCode=100001,AccountName="Lands",AccountOrder=7,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/23/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/23/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=8,CompanyId=1,AccountCode=100007,ParentAccountCode=100001,AccountName="Accumulated Depreciations",AccountOrder=8,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/24/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/24/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=9,CompanyId=1,AccountCode=100008,ParentAccountCode=100001,AccountName="Accumulated Depreciation-Furniture and Fixtures",AccountOrder=9,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/25/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/25/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=10,CompanyId=1,AccountCode=100009,ParentAccountCode=100001,AccountName="Accumulated Depreciation-Vehicles",AccountOrder=10,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/26/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/26/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=11,CompanyId=1,AccountCode=100010,ParentAccountCode=100001,AccountName="Accumulated Depreciation-Equipment",AccountOrder=11,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/27/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/27/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=12,CompanyId=1,AccountCode=100011,ParentAccountCode=100001,AccountName="Accumulated Depreciations-Building",AccountOrder=12,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/28/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/28/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=13,CompanyId=1,AccountCode=100012,ParentAccountCode=100001,AccountName="Accumulated Depreciation-Building Improvements",AccountOrder=13,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/29/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/29/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=14,CompanyId=1,AccountCode=110001,ParentAccountCode=100000,AccountName="Current Assets",AccountOrder=14,AccountClassID=1,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/30/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/30/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=15,CompanyId=1,AccountCode=110002,ParentAccountCode=110001,AccountName="Cash In Hand& Banks",AccountOrder=15,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	12/31/15 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	12/31/15 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=16,CompanyId=1,AccountCode=110003,ParentAccountCode=110002,AccountName="Cash on Hand A/C",AccountOrder=16,AccountClassID=1,AccountTypeCode=4,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/1/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/1/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=17,CompanyId=1,AccountCode=110004,ParentAccountCode=110002,AccountName="Regular Checking Account",AccountOrder=17,AccountClassID=1,AccountTypeCode=4,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/2/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/2/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=18,CompanyId=1,AccountCode=110005,ParentAccountCode=110002,AccountName="Savings Account",AccountOrder=18,AccountClassID=1,AccountTypeCode=4,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/3/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/3/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=19,CompanyId=1,AccountCode=110006,ParentAccountCode=110002,AccountName="Credit Card Account",AccountOrder=19,AccountClassID=1,AccountTypeCode=4,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/4/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/4/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=20,CompanyId=1,AccountCode=110007,ParentAccountCode=110002,AccountName="Petty Cash",AccountOrder=20,AccountClassID=1,AccountTypeCode=4,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/5/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/5/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=21,CompanyId=1,AccountCode=110008,ParentAccountCode=110001,AccountName="Term Deposits",AccountOrder=21,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/6/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/6/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=22,CompanyId=1,AccountCode=110009,ParentAccountCode=110001,AccountName="Provision For Bad Debts",AccountOrder=22,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/7/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/7/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=23,CompanyId=1,AccountCode=110010,ParentAccountCode=110001,AccountName="Accounts Receivable",AccountOrder=23,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/8/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/8/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=24,CompanyId=1,AccountCode=110011,ParentAccountCode=110001,AccountName="Commission Receivable",AccountOrder=24,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/9/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/9/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=25,CompanyId=1,AccountCode=110012,ParentAccountCode=110001,AccountName="Other Receivables",AccountOrder=25,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/10/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/10/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=26,CompanyId=1,AccountCode=110013,ParentAccountCode=110001,AccountName="Allowance for Doubtful Accounts",AccountOrder=26,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/11/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/11/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=27,CompanyId=1,AccountCode=110014,ParentAccountCode=110001,AccountName="Prepaid Expenses",AccountOrder=27,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/12/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/12/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=28,CompanyId=1,AccountCode=110015,ParentAccountCode=110001,AccountName="Employee Advances",AccountOrder=28,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/13/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/13/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=29,CompanyId=1,AccountCode=110016,ParentAccountCode=110001,AccountName="Inventory",AccountOrder=29,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/14/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/14/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=30,CompanyId=1,AccountCode=110017,ParentAccountCode=110001,AccountName="Suspense Account",AccountOrder=30,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/15/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/15/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=31,CompanyId=1,AccountCode=110018,ParentAccountCode=110001,AccountName="Goods Received Clearing Account",AccountOrder=31,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/16/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/16/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=32,CompanyId=1,AccountCode=110019,ParentAccountCode=110001,AccountName="Stocks of work in progress",AccountOrder=32,AccountClassID=1,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/17/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/17/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=33,CompanyId=1,AccountCode=200000,ParentAccountCode=0,AccountName="Liabilities",AccountOrder=33,AccountClassID=2,AccountTypeCode=1,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/18/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/18/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=34,CompanyId=1,AccountCode=200001,ParentAccountCode=200000,AccountName="Current Liabilities",AccountOrder=34,AccountClassID=2,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/19/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/19/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=35,CompanyId=1,AccountCode=200002,ParentAccountCode=200001,AccountName="Accounts Payable",AccountOrder=35,AccountClassID=2,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/20/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/20/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=36,CompanyId=1,AccountCode=200003,ParentAccountCode=200001,AccountName="Accrued Expenses",AccountOrder=36,AccountClassID=2,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/21/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/21/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=37,CompanyId=1,AccountCode=200004,ParentAccountCode=200001,AccountName="Wages Payable",AccountOrder=37,AccountClassID=2,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/22/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/22/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=38,CompanyId=1,AccountCode=200005,ParentAccountCode=200001,AccountName="Commision Payable",AccountOrder=38,AccountClassID=2,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/23/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/23/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=39,CompanyId=1,AccountCode=200006,ParentAccountCode=200001,AccountName="Deductions Payable",AccountOrder=39,AccountClassID=2,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/24/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/24/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=40,CompanyId=1,AccountCode=200007,ParentAccountCode=200001,AccountName="Health Insurance Payable",AccountOrder=40,AccountClassID=2,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/25/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/25/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=41,CompanyId=1,AccountCode=200008,ParentAccountCode=200001,AccountName="Tax Payables",AccountOrder=41,AccountClassID=2,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/26/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/26/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=42,CompanyId=1,AccountCode=200009,ParentAccountCode=200001,AccountName="Notes Payable",AccountOrder=42,AccountClassID=2,AccountTypeCode=3,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/27/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/27/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=43,CompanyId=1,AccountCode=300000,ParentAccountCode=0,AccountName="Equity",AccountOrder=43,AccountClassID=3,AccountTypeCode=1,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/28/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/28/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=44,CompanyId=1,AccountCode=300001,ParentAccountCode=300000,AccountName="Member Capital",AccountOrder=44,AccountClassID=3,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/29/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/29/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=45,CompanyId=1,AccountCode=300002,ParentAccountCode=300000,AccountName="Capital Surplus",AccountOrder=45,AccountClassID=3,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/30/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/30/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=46,CompanyId=1,AccountCode=300003,ParentAccountCode=300000,AccountName="Retained Surplus",AccountOrder=46,AccountClassID=3,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	1/31/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	1/31/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=47,CompanyId=1,AccountCode=300004,ParentAccountCode=300000,AccountName="Accumulated Profits",AccountOrder=47,AccountClassID=3,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/1/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/1/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=48,CompanyId=1,AccountCode=300005,ParentAccountCode=300000,AccountName="Accumulated Losses",AccountOrder=48,AccountClassID=3,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/2/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/2/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=49,CompanyId=1,AccountCode=400000,ParentAccountCode=0,AccountName="Revenues",AccountOrder=49,AccountClassID=4,AccountTypeCode=1,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/3/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/3/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=50,CompanyId=1,AccountCode=400001,ParentAccountCode=400000,AccountName="Sales A/C",AccountOrder=50,AccountClassID=4,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/4/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/4/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=51,CompanyId=1,AccountCode=400002,ParentAccountCode=400000,AccountName="Home Owners",AccountOrder=51,AccountClassID=4,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/5/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/5/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=52,CompanyId=1,AccountCode=400003,ParentAccountCode=400000,AccountName="Interest Income",AccountOrder=52,AccountClassID=4,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/6/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/6/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=53,CompanyId=1,AccountCode=400004,ParentAccountCode=400000,AccountName="Sales Discounts",AccountOrder=53,AccountClassID=4,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/7/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/7/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=54,CompanyId=1,AccountCode=400005,ParentAccountCode=400000,AccountName="Shipping and Handling",AccountOrder=54,AccountClassID=4,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/8/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/8/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=55,CompanyId=1,AccountCode=500000,ParentAccountCode=0,AccountName="Expenses",AccountOrder=55,AccountClassID=5,AccountTypeCode=1,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/9/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/9/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=56,CompanyId=1,AccountCode=500001,ParentAccountCode=500000,AccountName="General and Admin Expenses",AccountOrder=56,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/10/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/10/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=57,CompanyId=1,AccountCode=500002,ParentAccountCode=500001,AccountName="Salary Expenses",AccountOrder=57,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/11/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/11/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=58,CompanyId=1,AccountCode=500003,ParentAccountCode=500001,AccountName="Wages Expenses",AccountOrder=58,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/12/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/12/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=59,CompanyId=1,AccountCode=500004,ParentAccountCode=500001,AccountName="Employee Benefit Expenses",AccountOrder=59,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/13/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/13/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=60,CompanyId=1,AccountCode=500005,ParentAccountCode=500001,AccountName="Employee Benefit Expenses-Health Insurance",AccountOrder=60,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/14/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/14/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=61,CompanyId=1,AccountCode=500006,ParentAccountCode=500001,AccountName="Employee Benefit Expenses-Pension Plans",AccountOrder=61,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/15/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/15/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=62,CompanyId=1,AccountCode=500007,ParentAccountCode=500001,AccountName="Employee Benefit Expenses-Profit Sharing Plan",AccountOrder=62,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/16/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/16/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=63,CompanyId=1,AccountCode=500008,ParentAccountCode=500001,AccountName="Employee Benefit Expenses-Other",AccountOrder=63,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/17/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/17/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=64,CompanyId=1,AccountCode=500009,ParentAccountCode=500001,AccountName="Repair and Maintenance Expenses",AccountOrder=64,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/18/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/18/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=65,CompanyId=1,AccountCode=500010,ParentAccountCode=500001,AccountName="Repair and Maintenance Expenses-Office Equipment",AccountOrder=65,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/19/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/19/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=66,CompanyId=1,AccountCode=500011,ParentAccountCode=500001,AccountName="Repair and Maintenance Expenses-Vehicle",AccountOrder=66,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/20/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/20/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=67,CompanyId=1,AccountCode=500012,ParentAccountCode=500001,AccountName="Supplies Expenses-Office",AccountOrder=67,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/21/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/21/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=68,CompanyId=1,AccountCode=500013,ParentAccountCode=500001,AccountName="Telephone Expenses",AccountOrder=68,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/22/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/22/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=69,CompanyId=1,AccountCode=500014,ParentAccountCode=500001,AccountName="Postage Expenses",AccountOrder=69,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/23/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/23/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=70,CompanyId=1,AccountCode=500015,ParentAccountCode=500001,AccountName="Insurance Expenses-Vehicle",AccountOrder=70,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/24/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/24/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=71,CompanyId=1,AccountCode=500016,ParentAccountCode=500001,AccountName="Dues and Subscriptions Expenses",AccountOrder=71,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/25/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/25/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=72,CompanyId=1,AccountCode=500017,ParentAccountCode=500001,AccountName="Depreciation Expenses",AccountOrder=72,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/26/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/26/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=73,CompanyId=1,AccountCode=500018,ParentAccountCode=500001,AccountName="Meals and Entertainment Expenses",AccountOrder=73,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/27/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/27/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=74,CompanyId=1,AccountCode=500019,ParentAccountCode=500001,AccountName="Travel Expenses",AccountOrder=74,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/28/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/28/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=75,CompanyId=1,AccountCode=500020,ParentAccountCode=500001,AccountName="Utilities Expenses",AccountOrder=75,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	2/29/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	2/29/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=76,CompanyId=1,AccountCode=500021,ParentAccountCode=500001,AccountName="Legal and Professional Expenses",AccountOrder=76,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	3/1/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	3/1/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=77,CompanyId=1,AccountCode=500022,ParentAccountCode=500001,AccountName="Bank Charges",AccountOrder=77,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	3/2/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	3/2/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=78,CompanyId=1,AccountCode=500023,ParentAccountCode=500000,AccountName="Purchase A/C",AccountOrder=78,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	3/3/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	3/3/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=79,CompanyId=1,AccountCode=500024,ParentAccountCode=500000,AccountName="Cost of Goods Sold",AccountOrder=79,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	3/4/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	3/4/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=80,CompanyId=1,AccountCode=500025,ParentAccountCode=500000,AccountName="Purchase Discounts",AccountOrder=80,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	3/5/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	3/5/16 7:14 AM	",CultureInfo.InvariantCulture)},
 new Accounts {ID=81,CompanyId=1,AccountCode=500026,ParentAccountCode=500000,AccountName="Purchase price Variance",AccountOrder=81,AccountClassID=5,AccountTypeCode=2,OpenBalanceCredit=0,OpenBalanceDebit=0,StartingBalanceDebit=0,StartingBalanceCredit=0,CreatedBy="System",CreatedOn=DateTime.Parse("	3/6/16 7:14 AM	",CultureInfo.InvariantCulture),ModifiedBy="System", ModifiedOn=DateTime.Parse("	3/6/16 7:14 AM	",CultureInfo.InvariantCulture)}

            };

            accounts.ForEach(x => context.Accounts.Add(x));
            context.SaveChanges();

        }


    
}
}
